version: '3'
services:
  nginx-net:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: nginx-net:1.25.4
    container_name: nginx-net
    ports:
      - "5000:80"
    volumes:
      - ./nginx-cust.conf:/etc/nginx/conf.d/nginx-cust.conf
    depends_on:
      - net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
                      
  net:
    build:
      context: ./
      dockerfile: Dockerfile.new
    image: net:1.0
    container_name: net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1GB
